// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW4cu3TAwXUAcwf_ew6rFapkPQ_D6bR2g',
    appId: '1:379877928376:web:427ccab2169d551dca334d',
    messagingSenderId: '379877928376',
    projectId: 'chat-a2a3f',
    authDomain: 'chat-a2a3f.firebaseapp.com',
    storageBucket: 'chat-a2a3f.appspot.com',
    measurementId: 'G-CJQQGX4X4P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr7Hwb7s8jm7I6FbWB0m1a6sa_ZbpSOnI',
    appId: '1:379877928376:android:cdff3851e6c2877fca334d',
    messagingSenderId: '379877928376',
    projectId: 'chat-a2a3f',
    storageBucket: 'chat-a2a3f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGn2e1aRT8VWMkY-Yr45IMS2RPOpX8OHs',
    appId: '1:379877928376:ios:c05aa24660719886ca334d',
    messagingSenderId: '379877928376',
    projectId: 'chat-a2a3f',
    storageBucket: 'chat-a2a3f.appspot.com',
    iosClientId: '379877928376-3511kj5hm17pg1sa3h63j8k8ilj6927b.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGn2e1aRT8VWMkY-Yr45IMS2RPOpX8OHs',
    appId: '1:379877928376:ios:b6870dc4687cb3bfca334d',
    messagingSenderId: '379877928376',
    projectId: 'chat-a2a3f',
    storageBucket: 'chat-a2a3f.appspot.com',
    iosClientId: '379877928376-j2t4lh1d2ktufp5mo30oa8sigq606nsu.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
